<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "adw_goe_runes"
 *
 * Auto generated by Extension Builder 2016-11-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'RuneS Database',
	'description' => 'Provides the functionalities and database queries needed for the RuneS project',
	'category' => 'plugin',
	'author' => 'Jens Bahr',
	'author_email' => 'ju.bahr@isfas.uni-kiel.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);